pre_install() {
    xargs -r -a yay.txt yay -S -y --noconfirm --batchinstall --nouseask --noprovides --noremovemake --nodiffmenu --nocleanmenu --noeditmenu --noupgrademenu --requestsplitn 1000 spotify spotifyd github-desktop-bin teams spotify-tui joplin-desktop drawio-desktop snowflake write_stylus zotero
}
# post_install(){}
pre_upgrade() {
    pre_install
}
# post_upgrade(){}
# pre_remove(){}
# post_remove(){}
